---
# tasks file for harpreet.ocp-dns
  
- name: Install needed packages
  yum:
    name:
      - bind
      - bind-utils
      - libselinux-python
      - firewalld
    state: present

- name: starting firewalld
  service:
     name: "{{ item }}"
     state: started
     enabled: true
  with_items:
    - firewalld
    - named

- name: Write out named file
  template:
    src: named.conf.j2
    dest: /etc/named.conf
  notify:
    - restart bind

- name: Installing DNS Serialnumber generator
  copy:
    src: set-dns-serial.sh
    dest: /usr/local/bin/set-dns-serial.sh
    mode: '0555'

- name: Set zone serial number
  shell: "/usr/local/bin/set-dns-serial.sh"
  register: dymanicserialnumber

- name: Setting serial number as a fact
  set_fact:
    serialnumber: "{{ dymanicserialnumber.stdout }}"
  
- name: Write out "{{ dns.domain }}" zone file
  template:
    src: zonefile.j2
    dest: /var/named/zonefile.db
  notify:
    - restart bind
  
- name: Write out reverse zone file
  template:
    src: reverse.j2
    dest: /var/named/reverse.db
  notify:
    - restart bind
  
- name: Open up firewall ports
  firewalld:
    permanent: yes
    immediate: yes
    state: enabled
    port: "{{ item }}"
  with_items:
    - 53/tcp
    - 53/udp

- name: Best effort SELinux repair - DNS
  shell: "restorecon -vR /var/named || true"


- name: Set the local resolv.conf file
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
